### PR TITLE
fix an issue with wordle-game play: unable to start a new game

### LINKED ISSUE #1188: 🐛 [Bug report]: unable to interact after starting a new game in wordle-game play
### Descrcibe the bug?

If you successfully finish a game and then start a new wordle game, you can't enter new letters from keyboard or screen.
image

### Steps to reproduce the bug?

1. https://reactplay.io/plays/samirmishra27/wordle
2. Play a game
3. Finish it
4. Click on 'Start new game' on stats screen
5. Try to click on keyboard to enter letters from your keyboard.

### Expected behavior

Should be able to play normally and enter letters.

### Desktop (Please provide your system information)

- OS: Windows 11
- Browser: MS Edge
- Microsoft Edge Version 114.0.1823.43 (Official build) (64-bit)

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SamirMishra27**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This commit fixes an issue with Wordle Game Play where you are unable to enter new words after starting a new game.
The `gameOver` state will now be set to false when the component state resets.
Also, add missing key prop to iterative components of Wordle Row.

Fixes #1188

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Project was locally tested on my system, including the parts where the changes will be made.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@SamirMishra27 , can you link the relevant issue with this PR?

File: src/plays/wordle/Wordle.tsx [hunk 1]
```diff
@@ -71,6 +71,7 @@ function Wordle(props: any): JSX.Element {
     // This method removes all children from element node
     errorSlideRef.current.replaceChildren();
     setStats(null);
+    setGameOver(false);
```
Comment (Sachin-chaurasiya) [inline src/plays/wordle/Wordle.tsx:74]: @SamirMishra27 , why we are setting gameOver as false, could you please provide more details?

File: src/plays/wordle/Wordle.tsx [hunk 2]
```diff
@@ -254,6 +255,7 @@ function Wordle(props: any): JSX.Element {
                   {'QWERTYUIOP'.split('').map((alphabet) => (
                     <KeyboardKey
                       alphabet={alphabet}
+                      key={alphabet}
```
Comment (Sachin-chaurasiya) [inline src/plays/wordle/Wordle.tsx:258]: Thanks for taking care of this.

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

File: src/plays/wordle/Wordle.tsx (hunk 1 above)
Comment (SamirMishra27) [reply src/plays/wordle/Wordle.tsx:74]: `gameOver` is a state which indicates if the current game is over or not.
It's set to `true` after a game is finished.

If it is kept like that, then any unexpected keyboard key entries will be ignored here.
```ts


  function handleGameAction(action: WordleAction) {
    if (!action || gameOver) return;


    // Check and evaluate the guess
    if (action === 'Enter') {
```
So it's necessary to set it back to false then `reset()`'ing the data of all states when user starts a new game.

File: src/plays/wordle/components/WordleRow.tsx [hunk 3]
```diff
@@ -26,6 +26,7 @@ export default function WordleRow(props: { tileRow: TileRow; wordleWord: string
                   roll
                   correct={isCorrect}
                   index={index}
+                  key={`${index}-${letter}`}
```
Comment (Sachin-chaurasiya) [inline src/plays/wordle/components/WordleRow.tsx:29]: Never use index in key, can we just use the letter?

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]

File: src/plays/wordle/components/WordleRow.tsx (hunk 3 above)
Comment (SamirMishra27) [reply src/plays/wordle/components/WordleRow.tsx:29]: the letter might be an empty string. can we use `uuid` instead?

Comment (Sachin-chaurasiya) [reply src/plays/wordle/components/WordleRow.tsx:29]: Yes for now use uuid.

Comment (SamirMishra27) [reply src/plays/wordle/components/WordleRow.tsx]: Done!!

**Comment by atapas** [comment]
@Sachin-chaurasiya I am not looking into this one, assuming you are on it. I have approved the preview build.

**Review by Sachin-chaurasiya — APPROVED** [review]
Looks Good 👍
