### PR TITLE
Testimonials fixes 

### LINKED ISSUE #1194: 🐛 [Bug report]: Testimonials-fix
### Descrcibe the bug?

Error in providing testimonial 

### Steps to reproduce the bug?

1. Go to  https://reactplay.io/testimonials
2. Click on 
image
3. Give a long testimonial with line breaks. 
4. Error behaviour -> on submit, notice the error message that pops up

### Expected behavior

Currently, the UI doesn't display any information as to why the error is caused. A possible solution would be to notify users that whatever they are entering might cause an error and suggest ways to fix them.

### Desktop (Please provide your system information)

OS - Ubuntu 23.04
Browser - Chrome
Version 114.0.5735.133 (Official Build) (64-bit)

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yung-coder**
# Description

Fixes to be made in Testimonials 

Fixes #1194 

## Type of change

- [ ✅] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested by me in my local system 

# Checklist:

- [✅ ] I have performed a self-review of my own code
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have made corresponding changes to the documentation
- [✅ ] My changes generate no new warnings
- [ ✅] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes
- [✅ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/common/Testimonial/TestimonialModal.jsx [hunk 1]
```diff
@@ -40,21 +40,40 @@ export default function TestimonialModal({ isOpen, setIsOpen }) {
     fetchCategories();
   }, []);
 
+  function escapeNewLinesAndQuotes(inputString) {
+    const regex = /[\n\r"']/g;
+    const escapeMap = {
+      '\n': '\\n',
```
Comment (atapas) [inline src/common/Testimonial/TestimonialModal.jsx:46]: @yung-coder Are these the only characters to worry about? Then this fix is fine.

**Review by atapas — APPROVED** [review]
