### PR TITLE
Add Validation for URL Shortener Buttons and Fix Placeholder Visibility Issue

### LINKED ISSUE #1575: 🐛 [Bug report]: Add validation for URL Shortener buttons and fix placeholder visibility issue
### Descrcibe the bug?

In the current implementation of the URL Shortener, the following issues need to be addressed:
1. Validation for the "Shorten URL" button: The API is called even when the input field is empty.
2. Validation for the "Copy to Clipboard" Button: The button is enabled even without a valid shortened URL, allowing users to copy empty or invalid data.
3. User Experience Issue with Placeholder Text: The placeholder text in the input field is not fully visible; the text appears cut off, impacting usability and clarity for users.

### Steps to reproduce the bug?

1. Navigate to the URL Shortener page.
2. Leave the input field empty.
3. Click the "Shorten URL" button.
4. Observe that the API is called even with no input.
5. Without generating a shortened URL, click the "Copy to Clipboard" button.
6. Observe that the button attempts to copy empty or invalid data.
7. Look at the url shortener input field placeholder text and notice that it is partially visible or appears cut off.click the "Copy to Clipboard" button without generating a shortened URL

### Expected behavior

- For the "Shorten URL" button:
    - Button should be disabled if the input field is empty.

- For the "Copy to Clipboard" button:
   - Be hidden by default (when no shortened URL is generated).
   - Become visible only when a valid shortened URL is present.

- For the Input Field Placeholder:
  - Placeholder text should be fully visible and readable.
  - Adjust styling (e.g., padding, font size, or input box dimensions) to prevent text clipping.

### Desktop (Please provide your system information)

OS: macOS
Browser: Chrome

### Mobile (Please provide your device information)

_No response_

### Screenshot / Screenshare

Screenshot 2024-11-27 at 1 12 36 PM

### Relevant log output

_No response_

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anuj-kumary**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Summary of the Change:

1. Validation for the "Shorten URL" Button:

Added validation to prevent the API call when the input field is empty. Ensures that users cannot attempt to shorten a URL without providing valid input.

2. Validation for the "Copy to Clipboard" Button:

Modified the button's behavior to ensure it is only enabled when a valid shortened URL is present. Prevents users from copying empty or invalid data.

3. Fix for Placeholder Text Visibility:

Adjusted the styling of the input field to ensure the placeholder text is fully visible.
Enhances usability and improves the overall user experience by providing clear instructions through the placeholder.

Fixes #1575 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

1. Validation for the "Shorten URL" Button:

- Manually tested by attempting to click the button with an empty input field.
- Confirmed that the API call is not triggered when the input is invalid or empty.
- Verified functionality with valid URL inputs to ensure no regression.

2. Validation for the "Copy to Clipboard" Button:

- Confirmed that the button remains disabled when no valid URL is present.
- Ensured that valid data was successfully copied to the clipboard when a valid shortened URL was available.

3. Fix for Placeholder Text Visibility:

- Ensured that the text is no longer cut off and is fully readable at all times.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

https://github.com/user-attachments/assets/0c8260fd-45c3-4b25-9309-99ff4cd18cf8

Screenshot 2024-11-27 at 5 52 36 PM

### CODE REVIEW

File: src/plays/url-shortner/UrlShortner.jsx [hunk 1]
```diff
@@ -73,25 +83,32 @@ function UrlShortner(props) {
                   }}
                 />
                 <button
-                  class="ms-4 group relative h-12 w-48 overflow-hidden rounded-lg bg-white text-lg shadow"
+                  class="ms-4 group mt-4 relative h-12 px-6 overflow-hidden rounded-lg bg-white text-lg shadow"
                   onClick={handleSubmit}
                 >
                   <div class="absolute inset-0 w-3 bg-[#0087fe] transition-all duration-[250ms] ease-out group-hover:w-full" />
-                  <span class="relative text-black group-hover:text-white">Shorten This Link</span>
+                  <span class="relative text-black group-hover:text-white">Short URL</span>
```
Comment (Sachin-chaurasiya) [inline src/plays/url-shortner/UrlShortner.jsx:90]:
```suggestion
                  <span class="relative text-black group-hover:text-white">Shorten URL</span>
```

File: src/plays/url-shortner/UrlShortner.jsx [hunk 2]
```diff
@@ -73,25 +83,32 @@ function UrlShortner(props) {
...
-                <div className="relative px-4 py-2 bg-white shadow-lg rounded-xl  bg-clip-padding bg-opacity-60 border border-gray-200 text-slate-500">
-                  {shortenedLink ? shortenedLink : 'Shorten An URL First'}
+              {error && <div className="text-red-500 mt-5">{error}</div>}
+              {shortenedLink && (
+                <div className="mt-5">
+                  <p>Here's your shortened URL:</p>
+
+                  <div className="flex justify-center items-center">
+                    <div className="relative px-4 py-2 bg-white shadow-lg rounded-xl  bg-clip-padding bg-opacity-60 border border-gray-200 text-slate-500">
+                      {shortenedLink ? shortenedLink : 'Shorten An URL First'}
```
Comment (Sachin-chaurasiya) [inline src/plays/url-shortner/UrlShortner.jsx:100]:
```suggestion
                      {shortenedLink}
```

File: src/plays/url-shortner/UrlShortner.jsx [hunk 3]
```diff
@@ -73,25 +83,32 @@ function UrlShortner(props) {
...
+                    </div>
+                    <button
+                      className="border-2 px-5 py-2 ml-4 rounded-md font-medium 'border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white cursor-pointer"
+                      disabled={!shortenedLink}
```
Comment (Sachin-chaurasiya) [inline src/plays/url-shortner/UrlShortner.jsx:104]: We are already checking at the top that `shortenedLink` is available, so we don't need this piece of code. `disabled={!shortenedLink}`

**Review by Sachin-chaurasiya — APPROVED** [review]
