### PR TITLE
Issue 966 Removing hyphen for component name mapping

### LINKED ISSUE #966: 🐛 [Bug report]: Error in play if play name contains hyphen
**Describe the bug**

Play will be created in plays folder  but it will not be shown in playlist section in local environment.  

**To Reproduce**
1. Go to create play 
2. Click on create
3. Enter play name with hyphen  in it 

**Expected behavior**

Play should be available in playlist section in local environment.

**Screenshots**

none

**Desktop (please complete the following information):**
 - OS:  Ubuntu 
 - Browser: Firefox
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**

I would  like to explore why this is happening and try to fix it.

### PR DESCRIPTION
**Pull request by koustov**
> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #966 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

### CODE REVIEW

File: src/common/services/string.js [hunk 1]
```diff
@@ -44,10 +44,12 @@ export const toSanitized = (str) => {
   if (!str) {
     return '';
   }
+  str = str.replace(/-/g, '');
   // replace all special characters | symbols with a space
   str = str.replace(/[`~!@#$%^&*()_\-+=[\]{};:'"\\|/,.<>?\s]/g, ' ');
```
Comment (atapas) [inline src/common/services/string.js:49]: Why can't we make `-` as part of this regex batch itself? @koustov

Comment (koustov) [reply src/common/services/string.js:49]: that one is about converting to `space`, here we are removing hyphen

**Review by atapas — APPROVED** [review]
